// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Booking struct {
	ID               string          `json:"id"`
	GuestID          string          `json:"guestId"`
	RoomID           string          `json:"roomId"`
	CheckInDate      string          `json:"checkInDate"`
	CheckOutDate     string          `json:"checkOutDate"`
	TotalRoomPrice   float64         `json:"totalRoomPrice"`
	TotalAddonsPrice float64         `json:"totalAddonsPrice"`
	GrandTotal       float64         `json:"grandTotal"`
	Status           string          `json:"status"`
	Addons           []*BookingAddon `json:"addons,omitempty"`
}

type BookingAddon struct {
	ID             string  `json:"id"`
	AddonID        string  `json:"addonId"`
	Quantity       int     `json:"quantity"`
	PriceAtBooking float64 `json:"priceAtBooking"`
}

type BookingSummary struct {
	Booking      *Booking `json:"booking"`
	RoomDetails  *Room    `json:"roomDetails"`
	GuestDetails *Guest   `json:"guestDetails"`
}

type Guest struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	KtpNumber   string  `json:"ktpNumber"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

type Query struct {
}

type Room struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Location      string  `json:"location"`
	Description   *string `json:"description,omitempty"`
	PricePerNight float64 `json:"pricePerNight"`
	Status        string  `json:"status"`
}
